<!--HOW TO COMPLETE THIS FORM:-->

<!--
1. Checkboxes in this document appear as follows: 

- [ ] This is a checkbox 

To check a checkbox, replace [ ] by [x], as follows: 

- [x] This is a checked checkbox 

Note that older versions of RStudio (versions lower than 1.3) may not create a formatted checkbox but will leave the original characters, i.e., literally "[ ]" or "[x]". It's fine to submit a PDF in this form.
 
2. For text answers, simply type the relevant text in the areas indicated. A blank line starts a new paragraph. 
 
3. Comments (like these instructions) provide additional instructions throughout the form. There is no need to remove them; they will not appear in the compiled document. 

4. If you are comfortable with Markdown syntax, you may choose to include any Markdown-compliant formatting in the form. For example, you may wish to include R code chunks and compile this document in R Markdown.
-->

This form documents the artifacts associated with the article (i.e., the data and code supporting the computational findings) and describes how to reproduce the findings.


# Part 1: Data

- [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

<!--
If box above is checked and if no simulated/synthetic data files are provided by the authors, please skip directly to the Code section. Otherwise, continue.
-->

- [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

<!-- If data are simulated using random number generation, please be sure to set the random number seed in the code you provide -->

## Abstract

<!--
Provide a short (< 100 words), high-level description of the data
-->

## Availability


- [x] Data **are** publicly available.
- [ ] Data **cannot be made** publicly available.

If the data are publicly available, see the *Publicly available data* section. Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

- [x] Data are available online at: Michael W. McCracken's
website (https://research.stlouisfed.org/econ/mccracken/fred-databases/). We used the May 2022 version of FRED-MD.

- [x] Data are available as part of the paper’s supplementary material: We include FRED-MD_2022-05_preprocessed.csv (pre-processed data) and FRED-MD_2022-05.csv (raw data).

- [ ] Data are publicly available by request, following the process described here:

- [ ] Data are or will be made available through some other mechanism, described here:


<!-- If data are available by request to the authors or some other data owner, please make sure to explain the process of requesting access to the data. -->

### Non-publicly available data

<!--
The Journal of the American Statistical Association requires authors to make data accompanying their papers available to the scientific community except in cases where: 1) public sharing of data would be impossible, 2) suitable synthetic data are provided which allow the main analyses to be replicated (recognizing that results may differ from the "real" data analyses), and 3) the scientific value of the results and methods outweigh the lack of reproducibility.

Please discuss the lack of publicly available data. For example:
-	why data sharing is not possible,
-	what synthetic data are provided, and 
-	why the value of the paper's scientific contribution outweighs the lack of reproducibility.
-->

## Description

### File format(s)

<!--
Check all that apply
-->
- [x] CSV or other plain text.
- [ ] Software-specific binary format (.Rda, Python pickle, etc.): pkcle
- [ ] Standardized binary format (e.g., netCDF, HDF5, etc.): 
- [ ] Other (please specify):

### Data dictionary

<!--
A data dictionary provides information that allows users to understand the meaning, format, and use of the data.
-->

- [ ] Provided by authors in the following file(s):
- [ ] Data file(s) is(are) self-describing (e.g., netCDF files)
- [x] Available at the following URL: https://research.stlouisfed.org/econ/mccracken/fred-databases/.

### Additional Information (optional)

# Part 2: Code

## Abstract

The main scripts are ```lassoVAR.R``` and ```sqrtLassoVAR.R```, which include functions designed to 
estimate a VAR by weighted Lasso, post-Lasso and sqrt-Lasso going equation by 
equation. The basic inputs are a time series dataset (expecting: time as rows, series as columns) and the number of lags 
used in the autoregression (default: one). 
To get the weighted lasso, call ```fit <- lasso_var(data = data, q = 1, post = FALSE)```,
with post-Lasso arising from ```post = TRUE``` (default). The call for sqrt-Lasso is
analogous.
The basic outputs are the estimated coefficients (a matrix) and intercepts 
(a vector; included by default), which are extracted as ```fit$that``` and ```fit$intr```, 
respectively. These scripts call upon the (helper) functions in ```helper_functions.R```. The main and helper functions are used in the simulation study and empirical illustration in the paper.
The simulations are executed via ```runSim_v03.R```, which calls on ```simData.R``` for the
different simulation designs.
The empirical illustration is conducted via ```FRED-MD_forecasting_v02.R```.

## Description

### Code format(s)

<!--
Check all that apply
-->
- [x] Script files
    - [x] R
    - [ ] Python
    - [x] Matlab
    - [ ] Other: 
- [ ] Package
    - [ ] R
    - [ ] Python
    - [ ] MATLAB toolbox
    - [ ] Other: 
- [ ] Reproducible report 
    - [ ] R Markdown
    - [ ] Jupyter notebook
    - [ ] Other:
- [ ] Shell script
- [ ] Other (please specify): 

### Supporting software requirements

#### Version of primary software used

R version 4.4.1.

#### Libraries and dependencies used by the code

For calling main functions: glmnet (4.1.8), MASS (7.3.60.2), Matrix (1.7.0), stats (4.4.1).

For simulating data: Matrix (1.7.0), mvtnorm (1.3.2).

For parallel computing in simulation study/empirical illustration: doRNG (1.8.6), 
doParallel (1.0.17), foreach (1.5.1).

### Supporting system/hardware requirements (optional)

The simulations and empirical illustration were run on a Linux server with 
88 CPUs and 125 GB of RAM.

### Parallelization used

- [ ] No parallel code used
- [x] Multi-core parallelization on a single machine/node
    - Number of cores used: The main functions 
    ```lassoVAR.R``` and ```sqrtLassoVAR.R``` involve no parallelization.
    The simulations and empirical illustration were run on a Linux server with 
    88 CPUs and 125 GB of RAM.
- [ ] Multi-machine/multi-node parallelization 
    - Number of nodes and cores used: 

### License

- [x] MIT License (default)
- [ ] BSD 
- [ ] GPL v3.0
- [ ] Creative Commons
- [ ] Other: (please specify)


### Additional information (optional)

<!--
OPTIONAL: By default, submitted code will be published on the JASA GitHub repository
(http://github.com/JASA-ACS) as well as in the supplementary material. Authors are encouraged to
also make their code available in a public code repository, such as on GitHub, GitLab, or BitBucket.
If relevant, please provide unique identifier/DOI/version information (e.g., a Git commit ID,
branch, release, or tag). If the code and workflow are provided together, this section may be
omitted, with information provided in the "Location" section below.
-->

# Part 3: Reproducibility workflow

## Simulations
1. **Run the main simulations**:
   - Execute `runSim_v03.R` to run the simulations described in Section 6. (Execute from the root directory. Use ``setwd("..")`` to back up, if necessary.)
   - Save the workspace manually if not using Linux (via `save.image(...)`).
2. **Run the mark-up dependence simulations**:
   - Execute `markupDependence_v01.R` (from the root) to run the Supplementary Appendix H simulations investigating mark-up dependence.
3. **Generate figures**:
   - Run `createFigs_v07.R` to produce Figure 6.1 and Figure H.1.
   - Run `markupDependenceFigs_v02.R` to produce Figure H.2.

## Empirical Illustration
1. **(Optional) Pre-process the raw FRED-MD dataset (using Matlab)**:
   - Run `FREDMD_preprocess.m`, which calls upon `prepare_missing.m`, and `remove_outliers.m` in sequence.
2. **Conduct the forecasting exercise**:
   - Execute `FRED-MD_forecasting_v02.R`. (Execute from the root directory. Use `setwd("../..")` to back up, if necessary.)
   - The script will load the pre-processed data from `application/FRED/data` and save the workspace automatically (if in Linux).
3. **Generate figures**: Run `FRED-MD_figures_v02.R` to produce both parts of Figure 7.1.

<!-- ## Workflow

**To reproduce the simulations:**
Execute ```runSim_v03.R``` to run the main text simulations and
```markupDependence_v01.R``` for the mark-up dependence simulations, specifically.
To have access to ```lassoVAR.R``` and ```sqrtLassoVAR.R```, these scripts must be executed from the root directory.
Use ```setwd("..")``` to back up. When executed in a Linux environment, the script will
automatically save the workspaces in the simulations folder. If a different environment
is used, the workspace must be saved manually (via ```same.image(...)```). 
The figures included in the paper arise from calling the scripts ```createFigs_v07.R```
and ```markupDependenceFigs_v02.R``` from their folder, which load the relevant workspaces from 
the simulations folder and produce figures in the ```simulations/img``` folder.

**To reproduce the empirical illustration:**
Execute ```FRED-MD_forecasting_v02.R ``` 
(from the root directory via ```setwd("../..")```) to conduct the forecasting exercise.
The script loads the pre-processed data from the ```application/FRED/data``` folder
and automatically saves the workspace (if in Linux).
Run ```FRED-MD_figures_v02.R``` to produce the figures in the empirical illustration
in the ```application/FRED/img``` folder. -->

## Scope

The provided workflow reproduces:

- [ ] Any numbers provided in text in the paper
- [ ] The computational method(s) presented in the paper (i.e., code is provided that implements the method(s))
- [x] All tables and figures in the paper
- [ ] Selected tables and figures in the paper, as explained and justified below:

### Location

The workflow is available:

<!--
Check all that apply, and in the case of a Git repository include unique identifier, such as specific commit ID, branch, release, or tag.
-->
- [x] As part of the paper’s supplementary material.
- [ ] In this Git repository:
- [ ] Other (please specify):

<!--
Indicate where the materials (generally including the code, unless in a separate location and indicated in the previous section) are available. We strongly encourage authors to place their materials (but not large datasets) in a Git repository hosted on a site such as GitHub, GitLab, or BitBucket. If the repository is private during the review process, please indicate the location where it will be available publicly upon publication, and also include the materials as a zip file (e.g., obtained directly from the Git hosting site) as supplementary materials.
-->


### Format(s)

<!--
Check all that apply
-->
- [ ] Single master code file 
- [ ] Wrapper (shell) script(s)
- [x] Self-contained R Markdown file, Jupyter notebook, or other literate programming approach
- [ ] Text file (e.g., a readme-style file) that documents workflow
- [ ] Makefile
- [ ] Other (more detail in *Instructions* below)

### Instructions

<!--
Describe how to use the materials provided to reproduce analyses in the manuscript. Additional
details can be provided in file(s) accompanying the reproducibility materials. If no workflow is
provided, please state this and say why (e.g., if the paper contains no computational work).
-->

### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

- [ ] < 1 minute
- [ ] 1-10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] > 8 hours
- [x] Not feasible to run on a desktop machine, as described here: 
The simulations and empirical illustration were run on a Linux server with 
88 CPUs and 125 GB of RAM. In this environment, the runtimes for the main simulations, 
mark-up dependence simulations, and empirical illustration are 
approximately 32 hours, 3.5 hours, and 4 hours, respectively.


### Additional information (optional)

<!--
OPTIONAL: Additional documentation provided (e.g., R package vignettes, demos or other examples)
that show how to use the provided code/software in other settings.
-->

# Notes (optional)

<!--
OPTIONAL: Any other relevant information not covered on this form. If reproducibility materials are
not publicly available at the time of submission, please provide information here on how the
reviewers can view the materials.
-->
